export const ChannelTemplateMapping = {
  CONSUMER_INT: [
    "CardOrBank",
    "BankOrCard",
    "CardOnly",
    "AchOnly",
    "MinCardOnly",
    "MinAchOnly",
    "MinCardOnlyWithEdit",
    "CardOrExisting",
    "CardBankOrExisting",
    "BankCardOrExisting",
    "CardOnlyWithEdit",
    "AchOnlyWithEdit",
    "WalletMgmtNoAutopay",
  ],
  CBPC_QUICKPAY: ["CardOrBank"],
  CBPC_ONETIME: [
    "CardOrBank",
    "CardBankOrExisting",
    "BankCardOrExisting",
    "WalletMgmtNoAutopay",
  ],
  CBPC_RECURRING: ["CardOrBank", "WalletMgmtNoAutopay"],
  CAFE: [
    "CardOnly",
    "AchOnly",
    "CardOnlyWithEdit",
    "AchOnlyWithEdit",
    "MinCardOnlyWithEdit",
    "CardExpirationEdit",
  ],
  XFINITY_MOBILEBUS: ["MinCardOnly", "MinCardOnlyWithEdit"],
  XFINITY_MOBILE_TKN: ["MinCardOnly", "MinCardOnlyWithEdit"],
  XFINITY_MOBILEIG: [
    "CardOrExisting",
    "CardBankOrExisting",
    "BankCardOrExisting",
    "CardOnly",
  ],
  XFINITY_MOBILE_LITE_TKN: ["MinCardOnly"],
  XFINITY_MOBILEBUS_LITE: ["MinCardOnly"],
  MMCES_LITE: ["CardOrBank", "CardOnly", "AchOnly"],
  MMCES_ONETIME: ["CardOnly", "AchOnly", "MinCardOnly", "MinAchOnly"],
  SMB_LITE: ["CardOrBank", "CardOnly", "AchOnly"],
  SMB: ["CardOnly", "AchOnly"],
  PREPAID_TKN: ["CardOnly", "CardOrExisting", "CardExpirationEdit"],
  PREPAID_LITE: ["CardOnly", "CardExpirationEdit"],
  BSD_DIGITAL_SALES: ["CardOrBank", "BankOrCard"],
  WEB_MY_ACCT: [
    "CardExpirationEdit",
    "CardOnly",
    "AchOnly",
    "CardOrBank",
    "CardBankOrExisting",
    "BankCardOrExisting",
  ],
  WEB_LITE_MY_ACCT: ["CardOnly", "AchOnly", "CardOrBank"],
  EINSTEIN_CARE: [
    "CardOrBank",
    "CardBankOrExisting",
    "BankCardOrExisting",
    "CardOnlyWithEdit",
    "AchOnlyWithEdit",
  ],
  EINSTEIN: [
    "CardOrBank",
    "CardBankOrExisting",
    "BankCardOrExisting",
    "CardOnlyWithEdit",
    "AchOnlyWithEdit",
  ],
};
