import {ConfigData} from './config';

export const CURRENT_CHANNEL_DOMAIN = ConfigData.CURRENT_CHANNEL_DOMAIN;
export const ALLOWED_CHANNEL_DOMAIN_LIST = ConfigData.ALLOWED_CHANNEL_DOMAIN_LIST;
export const ALLOWED_CHANNEL_QUANTUM_METRIC = ConfigData.ALLOWED_CHANNEL_QUANTUM_METRIC;
export const BUSINESS_AUTO_PAY_CHANNEL_LIST = ConfigData.BUSINESS_AUTO_PAY_CHANNEL_LIST;
export const EVN_CPC_READY = 'CPC_READY';
export const EVN_CPC_FORM_SUBMIT = 'CPC_FORM_SUBMIT';
export const EVN_CPC_CONFIG_SUBMIT = 'CPC_CONFIG_SUBMIT';
export const ENV_EXPIRY_DATE_VALIDATION = 'EXPIRY_DATE_VALIDATION';
export const EVN_CPC_FORM_SUBMIT_RESPONSE = 'CPC_FORM_SUBMIT_RESPONSE';
export const EVN_CPC_PAGE_RESIZE = 'CPC_PAGE_RESIZE';
export const EVN_CPC_ERROR = 'CPC_ERROR';
export const EVN_CPC_FORM_PROCESSING = 'CPC_FORM_PROCESSING';
export const EVN_CPC_INFO_EVENT = 'CPC_INFO_EVENT';
export const EVN_CPC_MANAGE_PAYMENT_MODAL = 'CPC_MANAGE_PAYMENT_MODAL';
export const EVN_SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';
//events for local communication - within CPC
export const JUMP_HOSTED_CONTAINER = 'jump-hosted-container';
export const JUMP_CC_COMPONENT_LOADED = 'jump-cc-component-loaded';
export const JUMP_ACH_COMPONENT_LOADED = 'jump-ach-component-loaded';
export const JUMP_MIN_ACH_COMPONENT_LOADED = 'jump-min-ach-component-loaded';
//export const JUMP_MIN_ACH_COMPONENT_RESET = 'jump-min-ach-component-reset';
export const JUMP_DEFAULT_PAYMENT_COMPONENT_LOADED = 'jum-pdefault-payment-component-loaded';

export const JUMP_MIN_COMPONENT_LOADED = 'jump-min-component-loaded';
export const JUMP_CC_FORM_SUBMIT = 'jump-cc-form-submit';
export const JUMP_ACH_FORM_SUBMIT = 'jump-ach-form-submit';
export const JUMP_UPDATE_VIEW_MODEL = 'jump-update-view-model';
export const JUMP_ACH_TYPE_COMPONENT_LOADED = 'jump-ach-type-component-loaded';
export const JUMP_CC_CARE_COMPONENT_LOADED = 'jump-cc-care-component-loaded';
export const JUMP_ACH_CARE_COMPONENT_LOADED = 'jump-ach-care-component-loaded';
export const JUMP_CC_ADDRESS_COMPONENT_LOADED = 'jump-cc-address-component-loaded';
export const JUMP_ACH_ADDRESS_COMPONENT_LOADED = 'jump-ach-address-component-loaded';
export const JUMP_CARD_LIST_COMPONENT_LOADED = 'jump-card-list-component-loaded';
export const JUMP_CC_COMPONENT_RESET = 'jump-cc-component-reset';

export const JUMP_CC_ADDRESS_COMPONENT_RESET = 'jump-cc-address-component-reset';
export const JUMP_ACH_COMPONENT_RESET = 'jump-ach-component-reset';
export const JUMP_ACH_ADDRESS_COMPONENT_RESET = 'jump-ach-address-component-reset';
export const JUMP_ACCOUNT_TYPE_COMPONENT_RESET = 'jump-account-type-component-reset';
export const JUMP_ACH_DEFAULT_PAYMENT_COMPONENT_RESET = 'jump-ach-default-payment-component-reset';
export const JUMP_CC_DEFAULT_PAYMENT_COMPONENT_RESET = 'jump-cc-default-payment-component-reset';
export const JUMP_ADDRESS_OPTION_COMPONENT_LOADED = 'jump-address-option-component-loaded';
export const JUMP_CC_USERROLE_LIST_COMPONENT_LOADED = 'jump-cc-userrole-list-component-loaded';
export const JUMP_ACH_USERROLE_LIST_COMPONENT_LOADED = 'jump-ach-userrole-list-component-loaded';
export const JUMP_USERROLE_COMPONENT_LOADED = 'jump-userrole-component-loaded';
export const JUMP_CC_USERROLE_COMPONENT_RESET = 'jump-cc-userrole-component-reset';
export const JUMP_ACH_USERROLE_COMPONENT_RESET = 'jump-ach-userrole-component-reset';

export const CORPORATE_CHANNELS = ['mmces_lite','mmces_onetime', 'mmces_myaccount'];
export const ERR_PAYMENT_TYPE = 'Please select a payment type';

export const LABEL_FIRST_NAME = 'First or company name';
export const LABEL_LAST_NAME = 'Last name (if applicable)';

export const CUSTOMER_CLASS_RESIDENTIAL = 'residential';
export const CUSTOMER_CLASS_BUSINESS = 'business';

export const CPC_DEFAULT_ERROR_MESSAGE = 'We are unable to process payments at this time due to technical issues. Please try again later.';
export const ERR_PS_NO_WALLET_ENTRY_CODE_LIST = ['PAYMENT-8015', 'PAYMENT-9004', 'PAYMENT-8291', 'PAYMENT-8011'];
export const ERR_INVALID_CONFIG = 'JUMP web component config is invalid';
export const ERR_INVALID_CHANNEL_DATA =  'Channel data json is invalid';
export const ERR_INVALID_TEMPLATE =  'Unrecognized template value passed';

//DATA LAYER CONSTANTS
export const CPC_PAYMENT_METHOD_CARD_SELECT = 'CpcPaymentMethodCardSelect';
export const CPC_PAYMENT_METHOD_BANK_SELECT = 'CpcPaymentMethoBankSelect';
export const CPC_PAYMENT_METHOD_SELECT = 'CpcPaymentMethodSelect';
export const CPC_FORM_SUBMIT = 'CpcFormSubmit';
export const CPC_CARD_SUBMIT = 'CpcCardSubmit';
export const CPC_SORT_ATOZ = 'ATOZ';
export const CPC_SORT_ZTOA = 'ZTOA';
//export const CPC_CREDIT_CARD_FORM_SUBMIT = 'CpcCreditCardFormSubmit';
export const CPC_BANK_SUBMIT = 'CpcBankSubmit';
//export const CPC_BANK_FORM_SUBMIT = 'CpcBankFormSubmit';
export const CPC_ADDRESS_SELECT = 'CpcAddressSelect';
export const CPC_CREDIT_CARD_ADDRESS_SELECT = 'CpcCreditCardAddressSelect';
export const CPC_CREDIT_CARD_USERROLE_SELECT = 'CpcCreditCardUserroleSelect';
export const CPC_BANK_USERROLE_SELECT = 'CpcBankUserroleSelect';
export const CPC_BANK_ADDRESS_SELECT = 'CpcBankAddressSelect';
export const CPC_WALLET_MGMT_NO_AUTOPAY_BANK_FORM_CANCELED = 'CpcWalletMgmtNoAutopayBankFormCanceled';
export const CPC_WALLET_MGMT_NO_AUTOPAY_CARD_FORM_CANCELED = 'CpcWalletMgmtNoAutopayCardFormCanceled';
export const CPC_CARD_PRIMARY_ADDRESS_OPTION_SELECT = 'CpcCardPrimaryAddressOptionSelect';
export const CPC_BANK_PRIMARY_ADDRESS_OPTION_SELECT = 'CpcBankPrimaryAddressOptionSelect';
export const CPC_CARD_SECONDARY_ADDRESS_OPTION_SELECT = 'CpcCardSecondaryAddressOptionSelect';
export const CPC_BANK_SECONDARY_ADDRESS_OPTION_SELECT = 'CpcBankSecondaryAddressOptionSelect';
export const CPC_FORM_API_SUBMIT = 'CpcFormApiSubmit';
export const CPC_CREDIT_CARD_API_SUBMIT = 'CpcCreditCardApiSubmit';
export const CPC_BANK_API_SUBMIT = 'CpcBankApiSubmit';
export const CPC_BANK_ACCOUNT_TYPE_SELECT = 'CpcBankAccountTypeSelect';
export const CPC_MIN_CARD_SUBMIT = 'CpcMinCardSubmit';
export const CPC_MIN_CARD_EDIT_SUBMIT = 'CpcMinCardEditSubmit';
export const CPC_MIN_CARD_API_SUBMIT = 'CpcMinCardApiSubmit';
export const CPC_MIN_CARD_EDIT_API_SUBMIT = 'CpcMinCardEditApiSubmit';
export const CPC_MIN_BANK_SUBMIT = 'CpcMinBankSubmit';
export const CPC_CARD_OR_EXISTING_SUBMIT = 'CpcCardOrExistingSubmit';
export const CPC_CARD_BANK_OR_EXISTING_SUBMIT = 'CpcCardOrExistingSubmit';
export const CPC_WALLET_MGMT_NO_AUTOPAY_SUBMIT = 'CpcWalletMgmtNoAutopaySubmit';
export const CPC_WALLET_MGMT_NO_AUTOPAY_EDIT_API_SUBMIT = 'CpcWalletMgmtNoAutopayEditApiSubmit';
export const CPC_MIN_BANK_API_SUBMIT = 'CpcMinBankApiSubmit'; 
export const CPC_CARD_EDIT_API_SUBMIT = 'CpcCardEditApiSubmit';
export const CPC_BANK_EDIT_API_SUBMIT = 'CpcBankEditApiSubmit';
export const CPC_BANK_AUTO_PAY_SELECTED = 'CpcBankAutoPaySelected';
export const CPC_CARD_AUTO_PAY_SELECTED = 'CpcCardAutoPaySelected';
export const CPC_BANK_TERMS_AND_CONDITION_SELECTED = 'CpcBankTermsAndConditionSelected';
export const CPC_CARD_TERMS_AND_CONDITION_SELECTED = 'CpcCardTermsAndConditionSelected';
export const CPC_NEW_BANK_OPTION_SELECTED = 'CpcNewBankOptionSelected';
export const CPC_NEW_CARD_OPTION_SELECTED = 'CpcNewCardOptionSelected';
export const CPC_NEW_PAYMENT_OPTION_SELECTED = 'CpcNewPaymentOptionSelected';
export const CPC_EXISTING_PAYMENT_OPTION_SELECTED = 'CpcExistingPaymentOptionSelected';
export const CPC_STATE_SELECT = 'cpcStateSelect';
export const CPC_CARD_STATE_SELECT = 'cpcCardStateSelect';
export const CPC_BANK_STATE_SELECT = 'cpcBankStateSelect';
export const CPC_EXPIRATION_SELECT = 'cpcExpirationSelect';
export const CPC_CARD_EXP_MM_SELECT = 'cpcCardExpirationMMSelect';
export const CPC_CARD_EXP_YY_SELECT = 'cpcCardExpirationYYSelect';
export const CPC_CARD_EXPIRATION_EDIT_CANCEL_SELECTED = 'cpcCardExpirationEditCancelSelected';
export const CPC_CARD_EXPIRATION_EDIT_UPDATE_SELECTED = 'cpcCardExpirationEditUpdateSelected';
export const CPC_CARD_EXPIRATION_EDIT_EDIT_SELECTED = 'cpcCardExpirationEditEditSelected';
export const CPC_WALLET_MGMT_NO_AUTOPAY_EDIT_SELECTED = 'cpcWalletMgmtNoAutopayEditSelected';
export const CPC_WALLET_MGMT_NO_AUTOPAY_REMOVE_SELECTED = 'cpcWalletMgmtNoAutopayRemoveSelected';
export const CPC_CARD_EXPIRATION_EDIT_REMOVE_SELECTED = 'cpcCardExpirationEditRemoveSelected';
export const CPC_WALLET_MGMT_NO_AUTOPAY_UPDATE = 'cpcWalletMgmtNoAutopayUpdate';
// export const CPC_PAYMENT_TYPE_NOT_SELECTED = 'cpcPaymentTypeNotSelected';
export const CPC_CARD_OR_BANK_PAYMENT_TYPE_NOT_SELECTED = 'cpcCardOrBankPaymentTypeNotSelected'; 
export const CPC_CARD_BANK_OR_EXISTING_PAYMENT_TYPE_NOT_SELECTED = 'cpcCardBankOrExistingPaymentTypeNotSelected';
export const CPC_BANK_OR_CARD_PAYMENT_TYPE_NOT_SELECTED = 'cpcBankOrCardPaymentTypeNotSelected';
export const CPC_BANK_CARD_OR_EXISTING_PAYMENT_TYPE_NOT_SELECTED = 'cpcBankCardOrExistingPaymentTypeNotSelected';
export const CPC_CARD_OR_EXISTING_PAYMENT_TYPE_NOT_SELECTED = 'cpcCardOrExistingPaymentTypeNotSelected';
export const CARD_COMPONENT = 'card-component';
export const ACH_COMPONENT = 'ach-component';
export const MIN_ACH_COMPONENT = 'min-ach-component';
export const ADDRESS_COMPONENT = 'address-component';
export const ACCOUNT_TYPE_COMPONENT = 'account-type-component';
export const USERROLE_LIST_COMPONENT_CC = 'userrole-list-component-cc';
export const USERROLE_LIST_COMPONENT_ACH = 'userrole-list-component-ach';
export const TC_COMPONENT_CHECKED = 'tc-acccount-component';
export const SET_DEFAULT_COMPONENT_CHECKED = 'setdefault-acccount-component';
export const CPC_VISA = 'visa';
export const CPC_MASTERCARD = 'mastercard';
export const CPC_DISCOVER = 'discover';
export const CPC_AMERICAN_EXPRESS = 'american-express';
export const ACCEPTED_CARDS = [CPC_VISA, CPC_MASTERCARD, CPC_DISCOVER, CPC_AMERICAN_EXPRESS];
export const JUMP_NEW_CARD_OPTION = 'jump-new-card-option';
export const JUMP_NEW_BANK_OPTION = 'jump-new-bank-option';
export const JUMP_EXISTING_PAYMENT_RESPONSE_RECEIVED = 'jump-existing-payment-response-received';
export const JUMP_EXISTING_PAYMENT_NO_TOKEN_RECEIVED = 'jump-existing-payment-no-token-received';
export const JUMP_NEW_PAYMENT_OPTION = 'jump-new-payment-option';
export const JUMP_ERROR_MESSAGE_LOADED = 'jump-error-message-loaded';
export const JUMP_AUTO_PAY_COMPONENT_LOADED ='jump-auto-pay-component-loaded';
export const JUMP_AUTO_PAY_COMPONENT_RESET = 'jump-auto-pay-component-reset';
export const JUMP_ADD_TO_WALLET_SUCCESS = 'jump-add-to-wallet-success';
export const JUMP_AUTO_PAY_SUCCESS = 'jump-auto-pay-success';
export const JUMP_AUTO_PAY_ENROLL = 'jump-auto-pay-enroll';
export const CPC_AUTO_PAY_API_SUBMIT = 'CpcAutoPayApiSubmit';
export const JUMP_CC_AUTO_PAY_COMPONENT_LOADED = 'jump-cc-auto-pay-component-loaded';
export const JUMP_ACH_AUTO_PAY_COMPONENT_LOADED = 'jump-ach-auto-pay-component-loaded';
export const JUMP_CC_TC_COMPONENT_LOADED = 'jump-cc-terms-condition-component-loaded';
export const JUMP_ACH_TC_COMPONENT_LOADED = 'jump-ach-terms-condition-component-loaded';
export const JUMP_ACH_DEFAULT_PAYMENT_COMPONENT_LOADED = 'jump-ach-default-payment-component-loaded';
export const JUMP_CC_DEFAULT_PAYMENT_COMPONENT_LOADED = 'jump-cc-default-payment-component-loaded';
export const JUMP_TC_COMPONENT_RESET = 'jump-tc-component-reset';
export const JUMP_CARE_COMPONENT_RESET = 'jump-care-component-reset';
export const JUMP_CARD_BLOCKED = 'jump-card-blocked';
export const JUMP_BANK_BLOCKED = 'jump-bank-blocked';
export const ACH = 'ach';
export const CC = 'cc';
export const RESET = 'reset';
export const DELETE = 'delete';
export const BANK = 'bank';
export const CARD = 'card';
export const NEW_PAYMENT_OPTION_RADIO = 'radio';
export const NEW_PAYMENT_OPTION_BUTTON = 'button';
export const CARD_ONLY = 'CardOnly';
export const CARD_ONLY_WITH_EDIT = 'CardOnlyWithEdit';
export const ACH_ONLY_WITH_EDIT = 'AchOnlyWithEdit';
export const ACH_ONLY = 'AchOnly';
export const MIN_ACH_ONLY = 'MinAchOnly';
export const MIN_CARD_ONLY = 'MinCardOnly';
export const MIN_CARD_ONLY_WITH_EDIT = 'MinCardOnlyWithEdit';
export const CARD_OR_BANK = 'CardOrBank';
export const BANK_OR_CARD = 'BankOrCard';
export const CARD_OR_EXISTING = 'CardOrExisting';
export const CPC_CARD_BANK_OR_EXISTING = 'CardBankOrExisting';
export const CPC_BANK_CARD_OR_EXISTING = 'BankCardOrExisting';
export const DEFAULT_ACCOUNT_TYPE = 'default';
export const CORPORATE_DEFAULT_ACCOUNT_TYPE = 'corporatedefault';
export const CORPORATE_ACCOUNT_TYPE = 'corporate';
export const WALLET_MGMT_NO_AUTOPAY = 'WalletMgmtNoAutopay';
export const CARD_EXPIRATION_EDIT = 'CardExpirationEdit';
export const CPC_PAYMENT_FREQUENCY_ONETIME  = 'onetime';
export const TandCsViewTypeModal = 'modal';
export const JUMP_IGUARD_SERVICE = 'WalletServices';
export const JUMP_IGUARD_CC_METHOD = 'walletCard';
export const JUMP_IGUARD_ACH_METHOD = 'walletBank';
export const IGUARD_VALID_CARDS =['VISA', 'MASTERCARD', 'DISCOVER', 'AMERICANEXPRESS'];
export const IGUARD_CAPTURED_FIELDS_CC =  ['CREDITCARD', 'EXPMONTH', 'EXPYEAR', 'CVV'];
export const IGUARD_CAPTURED_FIELDS_ACH =  ['ROUTINGNUMBER', 'BANKACCOUNT'];
export const NEWPAYMENT = 'newpayment';
export const EXPIRATION_YEAR = 'expYY';
export const EXPIRATION_MONTH = 'expMM';
export const STORED_PAYMENT = 'storedPayment';

// Global Urls
export const CPC_GLOBAL_TEMPLATE_URL = 'templates/';
export const CPC_GLOBAL_IMAGES_BANK_URL = 'images/bank/';
export const CPC_GLOBAL_IMAGES_CARD_URL = 'images/cardtypes/';
export const CPC_GLOBAL_IMAGES_ICONS_URL = 'images/icons/';
export const CPC_GLOBAL_IMAGES_POPUP_URL = 'images/popups/';
export const CPC_GLOBAL_ERROR_MAPPING_URL = 'error_mapping/cpc-error-mapping.json';
export const CPC_GLOBAL_CONTENT_MAPPING_URL = 'content/cpc-content-mapping.json';

export const JUMP_PAYMENT_CLICKED = 'jump-payment-clicked';
// Base Vm Service
export const CARD_ONLY_VIEWMODAL_SERVICE = 'CardOnlyViewModelService';
export const ACH_ONLY_VIEWMODAL_SERVICE = 'AchOnlyViewModelService';
export const ACCOUNT_TYPE_VIEWMODAL_SERVICE = 'AccountTypeViewModelService';
export const ADDRESS_ONLY_VIEWMODAL_SERVICE = 'AddressOnlyViewModelService';
export const MIN_CARD_ONLY_VIEWMODAL_SERVICE = 'MinCardOnlyViewModelService';
export const MIN_ACH_ONLY_VIEWMODAL_SERVICE = 'MinAchOnlyViewModelService'; 
export const CARD_LIST_VIEWMODAL_SERVICE = 'CardListViewModelService';
export const AUTO_PAY_VIEWMODAL_SERVICE = 'AutoPayViewModelService'; 
export const TERMS_AND_CONDITION_VIEWMODAL_SERVICE = 'TermsAndConditionViewModelService';
export const DEFAULT_PAYMENT_VIEWMODAL_SERVICE = 'DefaultPaymentViewModelService';
export const CARE_VIEWMODAL_SERVICE = 'CareViewModelService';
export const USERROLE_LIST_VIEWMODAL_SERVICE = 'UserroleListViewModelService';


export const CARD_ONLY_WEB_COMPONENT =  'CardOnlyWebComponent';
export const ACH_ONLY_WEB_COMPONENT = 'AchOnlyWebComponent'; 
export const ADDRESS_WEB_COMPONENT_CC = 'AddressWebComponentCc';  
export const ADDRESS_WEB_COMPONENT_ACH = 'AddressWebComponentAch';
export const AUTO_PAY_WEB_COMPONENT_CC = 'AutoPayWebComponentCc'; 
export const AUTO_PAY_WEB_COMPONENT_ACH = 'AutoPayWebComponentAch'; 
export const CARD_LIST_WEB_COMPONENT = 'CardListWebComponent';
export const DEFAULT_PAYMENT_WEB_COMPONENT_CC = 'DefaultPaymentWebComponentCc';
export const DEFAULT_PAYMENT_WEB_COMPONENT_ACH = 'DefaultPaymentComponentAch'; 
export const TERMS_WEB_COMPONENT_CC = 'TermsWebComponentCc'; 
export const TERMS_WEB_COMPONENT_ACH = 'TermsWebComponentAch';
export const CARE_WEB_COMPONENT_CC = 'CareWebComponentCc';
export const CARE_WEB_COMPONENT_ACH = 'CareWebComponentAch';
export const USERROLE_LIST_WEB_COMPONENT_CC = 'UserroleListWebComponentCc';
export const USERROLE_LIST_WEB_COMPONENT_ACH = 'UserroleListWebComponentAch';

export const MIN_ACH_ONLY_WEB_COMPONENT = 'MinAchOnlyWebComponent';
export const MIN_CARD_ONLY_WEB_COMPONENT = 'MinCardOnlyWebComponent';
export const ACCOUNT_TYPE_WEB_COMPONENT = 'AccountTypeWebComponent';

export const ITEM_KEY_STATE = 'state';
export const ITEM_KEY_FIRST_NAME = 'firstname';
export const ITEM_KEY_LAST_NAME = 'lastname';
export const ITEM_KEY_ADDRESS_LINE_2 = 'addressline2';

export const JUMP_UPDATE_VIEW_MODEL_USERROLE_ACH ='userrole-ach';
export const JUMP_UPDATE_VIEW_MODEL_USERROLE_CC ='userrole-cc';

export const STORE_PAYMENT_ERROR_MAP = 'storePayment';
export const USER_ROLE_ERROR_MAP = 'userrole';

// export const MAX_LENGTH_VISA_AND_DISCOVER = 23; // 19 FOR NUMBER, 4 trails
// export const MAX_LENGTH_VISA_AND_DISCOVER_TRAILS = 4; // 16 FOR NUMBER, 3 trails
export const MAX_LENGTH_VISA_AND_DISCOVER = 19; // 16 FOR NUMBER, 3 trails
export const MAX_LENGTH_VISA_AND_DISCOVER_TRAILS = 3; // 16 FOR NUMBER, 3 trails

export const MAX_LENGTH_AMEX = 17; // 15 FOR NUMBER, 2 trails
export const MAX_LENGTH_AMEX_TRAILS = 2; // 15 FOR NUMBER, 2 trails
export const MAX_LENGTH_MASTERCARD = 19; // 16 FOR NUMBER, 3 trails
export const MAX_LENGTH_MASTERCARD_TRAILS =3; // 16 FOR NUMBER, 3 trails