platform: linux

image_resource:
  type: registry-image
  source:
    repository: hub.comcast.net/xia/concourse/jump-box
    tag: latest

inputs:
- name: git-pull-request
- name: commit-id
- name: pull-request-id
- name: concourse-repo

outputs:
 - name: build
 
params:
   artifactory_url: ((artifactory.url))
   artifactory_user: ((artifactory.user))
   artifactory_password: ((artifactory.password))
   sonar_login: ((sonar.user))
   sonar_host_url: ((sonar.url))
   
run:
  path: concourse-repo/scripts/build_pr.sh
  args: [ ((artifactory.url)) ((artifactory.user)) ((artifactory.password)) ((sonar.user)) ((sonar.url)) ]
