platform: linux

image_resource:
  type: registry-image
  source:
    repository: hub.comcast.net/xia/concourse/cpc-service-box
    tag: latest

params:
  cf_user: ((service-account.username))
  cf_password: ((service-account.secret))
  cf_path: ((cloud-foundry/method-of-payment-service/common.cf_path))
  cf_domain_nonprod: ((cloud-foundry/method-of-payment-service/non-prod/common.cf_domain))
  cf_org_nonprod: ((cloud-foundry/method-of-payment-service/non-prod/common.cf_org))
  cf_space_dev: ((cloud-foundry/method-of-payment-service/non-prod/development.cf_space))
  cf_host_dev: ((cloud-foundry/method-of-payment-service/non-prod/development.cf_host))
  cf_space_int: ((cloud-foundry/method-of-payment-service/non-prod/integration.cf_space))
  cf_host_int: ((cloud-foundry/method-of-payment-service/non-prod/integration.cf_host))
  environment: ((environment))

run:
  path: concourse-repo/scripts/rollback_service.sh
  args: [ ((service-account.username))
            ((service-account.secret))
            ((cloud-foundry/method-of-payment-service/common.cf_path))
            ((cloud-foundry/method-of-payment-service/non-prod/common.cf_domain))
            ((cloud-foundry/method-of-payment-service/non-prod/common.cf_org))
            ((cloud-foundry/method-of-payment-service/non-prod/development.cf_space))
            ((cloud-foundry/method-of-payment-service/non-prod/development.cf_host))
            ((cloud-foundry/method-of-payment-service/non-prod/integration.cf_space))
            ((cloud-foundry/method-of-payment-service/non-prod/integration.cf_host))
            ((environment)) ]